
cd "E:\Facultate\TW-SkIns-ATAV\G V2.0"
start cmd /C "nodemon server.js"
cd "E:\Facultate\TW-SkIns-ATAV\server\microservicii\achievements"
start cmd /C "nodemon achievements.js"
cd "E:\Facultate\TW-SkIns-ATAV\server\microservicii\API_Lang"
start cmd /C "http-server -p 9010"
cd "E:\Facultate\TW-SkIns-ATAV\server\microservicii\courses"
start cmd /C "nodemon courses.js"
cd "E:\Facultate\TW-SkIns-ATAV\server\microservicii\guitar"
start cmd /C "http-server -p 9030"
cd "E:\Facultate\TW-SkIns-ATAV\server\microservicii\profile"
start cmd /C "nodemon profile.js"
cd "E:\Facultate\TW-SkIns-ATAV\server\microservicii\python"
start cmd /C "nodemon microserviciu-python.js"
cd "E:\Facultate\TW-SkIns-ATAV\server\microservicii\register"
start cmd /C "nodemon register.js"
cd "E:\Facultate\TW-SkIns-ATAV\server\microservicii\subscribe"
start cmd /C "nodemon subscribeServer.js"
cd "E:\Facultate\TW-SkIns-ATAV\server\microservicii\testimoniale"
start cmd /C "nodemon testimoniale.js"